services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: vaultadmin         # админ, которым Vault будет создавать временные юзеры
      POSTGRES_PASSWORD: vaultadmin
      POSTGRES_DB: re
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  vault:
    image: hashicorp/vault:1.16
    command: server -dev -dev-root-token-id=devroot -dev-listen-address=0.0.0.0:8200
    environment:
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports: ["8200:8200"]
    cap_add: ["IPC_LOCK"]

  api:
    build: ./app
    depends_on:
      db: { condition: service_started }
      vault: { condition: service_started }
    env_file: .env
    environment:
      # адрес и токен Vault (в dev так, в проде будет другой auth-метод)
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "devroot"
      VAULT_DB_ROLE: "app-readwrite"   # имя роли в Vault
    ports: ["8000:8000"]
    command: ["sh","-c","uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload"]
    volumes:
      - ./app:/app

volumes:
  pgdata:
